// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEngineState() {
  return window['go']['main']['App']['GetEngineState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Hotkeys() {
  return window['go']['main']['App']['Hotkeys']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
