// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {settingsmanager} from '../models';

export function GetEngineState():Promise<engine.EngineState>;

export function GetVersion():Promise<string>;

export function Hotkeys():Promise<void>;

export function LoadSettings():Promise<settingsmanager.Settings>;

export function SaveSettings(arg1:settingsmanager.Settings):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function TogglePause():Promise<void>;
